# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lander/gait_plan_msgs.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class gait_plan_msgs(genpy.Message):
  _md5sum = "b401d108fe4e07f912067db7a9916b5e"
  _type = "lander/gait_plan_msgs"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# 客户端请求
# 0:getpos; 1:init; 2:planfoot; 3:planmotion
int32 command_index
# For planfoot
int32 leg_index
float64[3] foot1_motion
float64[3] foot2_motion
float64[3] foot3_motion
float64[3] foot4_motion
# For planmotion
int32 data_num
float64[] foot1_trace_x
float64[] foot1_trace_y
float64[] foot1_trace_z
float64[] foot2_trace_x
float64[] foot2_trace_y
float64[] foot2_trace_z
float64[] foot3_trace_x
float64[] foot3_trace_y
float64[] foot3_trace_z
float64[] foot4_trace_x
float64[] foot4_trace_y
float64[] foot4_trace_z

"""
  __slots__ = ['command_index','leg_index','foot1_motion','foot2_motion','foot3_motion','foot4_motion','data_num','foot1_trace_x','foot1_trace_y','foot1_trace_z','foot2_trace_x','foot2_trace_y','foot2_trace_z','foot3_trace_x','foot3_trace_y','foot3_trace_z','foot4_trace_x','foot4_trace_y','foot4_trace_z']
  _slot_types = ['int32','int32','float64[3]','float64[3]','float64[3]','float64[3]','int32','float64[]','float64[]','float64[]','float64[]','float64[]','float64[]','float64[]','float64[]','float64[]','float64[]','float64[]','float64[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       command_index,leg_index,foot1_motion,foot2_motion,foot3_motion,foot4_motion,data_num,foot1_trace_x,foot1_trace_y,foot1_trace_z,foot2_trace_x,foot2_trace_y,foot2_trace_z,foot3_trace_x,foot3_trace_y,foot3_trace_z,foot4_trace_x,foot4_trace_y,foot4_trace_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(gait_plan_msgs, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.command_index is None:
        self.command_index = 0
      if self.leg_index is None:
        self.leg_index = 0
      if self.foot1_motion is None:
        self.foot1_motion = [0.] * 3
      if self.foot2_motion is None:
        self.foot2_motion = [0.] * 3
      if self.foot3_motion is None:
        self.foot3_motion = [0.] * 3
      if self.foot4_motion is None:
        self.foot4_motion = [0.] * 3
      if self.data_num is None:
        self.data_num = 0
      if self.foot1_trace_x is None:
        self.foot1_trace_x = []
      if self.foot1_trace_y is None:
        self.foot1_trace_y = []
      if self.foot1_trace_z is None:
        self.foot1_trace_z = []
      if self.foot2_trace_x is None:
        self.foot2_trace_x = []
      if self.foot2_trace_y is None:
        self.foot2_trace_y = []
      if self.foot2_trace_z is None:
        self.foot2_trace_z = []
      if self.foot3_trace_x is None:
        self.foot3_trace_x = []
      if self.foot3_trace_y is None:
        self.foot3_trace_y = []
      if self.foot3_trace_z is None:
        self.foot3_trace_z = []
      if self.foot4_trace_x is None:
        self.foot4_trace_x = []
      if self.foot4_trace_y is None:
        self.foot4_trace_y = []
      if self.foot4_trace_z is None:
        self.foot4_trace_z = []
    else:
      self.command_index = 0
      self.leg_index = 0
      self.foot1_motion = [0.] * 3
      self.foot2_motion = [0.] * 3
      self.foot3_motion = [0.] * 3
      self.foot4_motion = [0.] * 3
      self.data_num = 0
      self.foot1_trace_x = []
      self.foot1_trace_y = []
      self.foot1_trace_z = []
      self.foot2_trace_x = []
      self.foot2_trace_y = []
      self.foot2_trace_z = []
      self.foot3_trace_x = []
      self.foot3_trace_y = []
      self.foot3_trace_z = []
      self.foot4_trace_x = []
      self.foot4_trace_y = []
      self.foot4_trace_z = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2i().pack(_x.command_index, _x.leg_index))
      buff.write(_get_struct_3d().pack(*self.foot1_motion))
      buff.write(_get_struct_3d().pack(*self.foot2_motion))
      buff.write(_get_struct_3d().pack(*self.foot3_motion))
      buff.write(_get_struct_3d().pack(*self.foot4_motion))
      _x = self.data_num
      buff.write(_get_struct_i().pack(_x))
      length = len(self.foot1_trace_x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.foot1_trace_x))
      length = len(self.foot1_trace_y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.foot1_trace_y))
      length = len(self.foot1_trace_z)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.foot1_trace_z))
      length = len(self.foot2_trace_x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.foot2_trace_x))
      length = len(self.foot2_trace_y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.foot2_trace_y))
      length = len(self.foot2_trace_z)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.foot2_trace_z))
      length = len(self.foot3_trace_x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.foot3_trace_x))
      length = len(self.foot3_trace_y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.foot3_trace_y))
      length = len(self.foot3_trace_z)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.foot3_trace_z))
      length = len(self.foot4_trace_x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.foot4_trace_x))
      length = len(self.foot4_trace_y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.foot4_trace_y))
      length = len(self.foot4_trace_z)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.foot4_trace_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.command_index, _x.leg_index,) = _get_struct_2i().unpack(str[start:end])
      start = end
      end += 24
      self.foot1_motion = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.foot2_motion = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.foot3_motion = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.foot4_motion = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 4
      (self.data_num,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot1_trace_x = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot1_trace_y = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot1_trace_z = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot2_trace_x = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot2_trace_y = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot2_trace_z = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot3_trace_x = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot3_trace_y = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot3_trace_z = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot4_trace_x = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot4_trace_y = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot4_trace_z = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2i().pack(_x.command_index, _x.leg_index))
      buff.write(self.foot1_motion.tostring())
      buff.write(self.foot2_motion.tostring())
      buff.write(self.foot3_motion.tostring())
      buff.write(self.foot4_motion.tostring())
      _x = self.data_num
      buff.write(_get_struct_i().pack(_x))
      length = len(self.foot1_trace_x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.foot1_trace_x.tostring())
      length = len(self.foot1_trace_y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.foot1_trace_y.tostring())
      length = len(self.foot1_trace_z)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.foot1_trace_z.tostring())
      length = len(self.foot2_trace_x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.foot2_trace_x.tostring())
      length = len(self.foot2_trace_y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.foot2_trace_y.tostring())
      length = len(self.foot2_trace_z)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.foot2_trace_z.tostring())
      length = len(self.foot3_trace_x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.foot3_trace_x.tostring())
      length = len(self.foot3_trace_y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.foot3_trace_y.tostring())
      length = len(self.foot3_trace_z)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.foot3_trace_z.tostring())
      length = len(self.foot4_trace_x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.foot4_trace_x.tostring())
      length = len(self.foot4_trace_y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.foot4_trace_y.tostring())
      length = len(self.foot4_trace_z)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.foot4_trace_z.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.command_index, _x.leg_index,) = _get_struct_2i().unpack(str[start:end])
      start = end
      end += 24
      self.foot1_motion = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.foot2_motion = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.foot3_motion = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.foot4_motion = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 4
      (self.data_num,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot1_trace_x = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot1_trace_y = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot1_trace_z = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot2_trace_x = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot2_trace_y = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot2_trace_z = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot3_trace_x = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot3_trace_y = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot3_trace_z = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot4_trace_x = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot4_trace_y = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.foot4_trace_z = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
