// Generated by gencpp from file lander/gait_feedback_msgs.msg
// DO NOT EDIT!


#ifndef LANDER_MESSAGE_GAIT_FEEDBACK_MSGS_H
#define LANDER_MESSAGE_GAIT_FEEDBACK_MSGS_H

#include <ros/service_traits.h>


#include <lander/gait_feedback_msgsRequest.h>
#include <lander/gait_feedback_msgsResponse.h>


namespace lander
{

struct gait_feedback_msgs
{

typedef gait_feedback_msgsRequest Request;
typedef gait_feedback_msgsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gait_feedback_msgs
} // namespace lander


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lander::gait_feedback_msgs > {
  static const char* value()
  {
    return "27d686c76786081478a2ea2d859bdf1f";
  }

  static const char* value(const ::lander::gait_feedback_msgs&) { return value(); }
};

template<>
struct DataType< ::lander::gait_feedback_msgs > {
  static const char* value()
  {
    return "lander/gait_feedback_msgs";
  }

  static const char* value(const ::lander::gait_feedback_msgs&) { return value(); }
};


// service_traits::MD5Sum< ::lander::gait_feedback_msgsRequest> should match
// service_traits::MD5Sum< ::lander::gait_feedback_msgs >
template<>
struct MD5Sum< ::lander::gait_feedback_msgsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lander::gait_feedback_msgs >::value();
  }
  static const char* value(const ::lander::gait_feedback_msgsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lander::gait_feedback_msgsRequest> should match
// service_traits::DataType< ::lander::gait_feedback_msgs >
template<>
struct DataType< ::lander::gait_feedback_msgsRequest>
{
  static const char* value()
  {
    return DataType< ::lander::gait_feedback_msgs >::value();
  }
  static const char* value(const ::lander::gait_feedback_msgsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lander::gait_feedback_msgsResponse> should match
// service_traits::MD5Sum< ::lander::gait_feedback_msgs >
template<>
struct MD5Sum< ::lander::gait_feedback_msgsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lander::gait_feedback_msgs >::value();
  }
  static const char* value(const ::lander::gait_feedback_msgsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lander::gait_feedback_msgsResponse> should match
// service_traits::DataType< ::lander::gait_feedback_msgs >
template<>
struct DataType< ::lander::gait_feedback_msgsResponse>
{
  static const char* value()
  {
    return DataType< ::lander::gait_feedback_msgs >::value();
  }
  static const char* value(const ::lander::gait_feedback_msgsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LANDER_MESSAGE_GAIT_FEEDBACK_MSGS_H
